version: "2.1"
services:
  resilio-sync:
    image: lscr.io/linuxserver/resilio-sync:latest
    container_name: resilio-sync
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /volume1/docker/resilio/config:/config
      - /volume1/docker/resilio/downloads:/downloads
      - /volume1/docker/resilio/data:/sync
    ports:
      - 8888:8888
      - 55555:55555
    restart: unless-stopped
